import { useCallback, useEffect, useState } from 'react';
import { NavLink, Route, Routes } from 'react-router-dom';
import { Activity, AlertTriangle, Archive, BarChart3, Building2, House, LayoutDashboard, Map as MapIcon, Shield, Truck } from 'lucide-react';
import { getState } from './services/api';
import { useCrisisWebSocket } from './hooks/useCrisisWebSocket';
import { Dashboard, CrisisPage, MapPage, AgentsPage, ResourcesPage, SheltersPage, HospitalsPage, AlertsPage, AuditPage, MetricsPage, MonitorPage } from './pages/Pages';
const nav = [['Dashboard', '/dashboard', LayoutDashboard], ['Active Crisis', '/crisis', AlertTriangle], ['Map', '/map', MapIcon], ['Agents', '/agents', Activity], ['Resources', '/resources', Truck], ['Shelters', '/shelters', House], ['Hospitals', '/hospitals', Building2], ['Alerts', '/alerts', Shield], ['Audit Log', '/audit', Archive], ['Metrics', '/metrics', BarChart3], ['System Monitor', '/monitor', Activity]] as const;
export default function App() {
  const [state, setState] = useState<any>(null); const [error, setError] = useState(''); const refresh = useCallback((next: any) => setState(next), []);
  useEffect(() => { getState().then(setState).catch(() => setError('Backend connection lost. Start FastAPI on port 8000.')); }, []); useCrisisWebSocket(refresh);
  if (!state) return <div className="app"><div className="empty" style={{ padding: 40 }}>Connecting to CrisisMind backend... {error && <span className="error">{error}</span>}</div></div>;
  return <div className="app"><header className="topbar"><div className="brand"><div className="brand-mark">*</div><div>CrisisMind AI<small>Emergency Decision Support Center</small></div></div><div className="top-meta"><span className="online">SYSTEM ONLINE</span><span>ROLE - EMERGENCY OPERATOR</span><span>{state.ai_mode}</span></div></header><div className="shell"><aside className="sidebar"><div className="nav-label">COMMAND CENTER</div>{nav.map(([name, path, Icon]) => <NavLink className="nav-item" to={path} key={path}><Icon size={16} />{name}</NavLink>)}<div className="footer-note">AI-generated recommendations are decision-support outputs. Critical emergency actions require authorization by trained personnel.</div></aside><main className="main">{error && <div className="error">{error}</div>}<Routes><Route path="/" element={<Dashboard state={state} setState={setState} />} /><Route path="/dashboard" element={<Dashboard state={state} setState={setState} />} /><Route path="/crisis" element={<CrisisPage state={state} setState={setState} />} /><Route path="/map" element={<MapPage state={state} />} /><Route path="/agents" element={<AgentsPage state={state} />} /><Route path="/resources" element={<ResourcesPage state={state} setState={setState} />} /><Route path="/shelters" element={<SheltersPage state={state} setState={setState} />} /><Route path="/hospitals" element={<HospitalsPage state={state} setState={setState} />} /><Route path="/alerts" element={<AlertsPage state={state} setState={setState} />} /><Route path="/audit" element={<AuditPage state={state} />} /><Route path="/metrics" element={<MetricsPage state={state} />} /><Route path="/monitor" element={<MonitorPage state={state} />} /></Routes></main></div></div>;
}
